# Default values for devops-bookstore-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  
  repository: devopsupskillregistryvhkxq.azurecr.io/devopsupskill/devops-bookstore-api:1.0
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  containerPort: 5000
  livenessProbe: /books
  readinessProbe: /books
